# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e090e7b4b9816ca1bdbef2aa18d38f18966e4133712ff931aba9dd711456556ca8b9603f5e72295c526bc68af22e85a91524c77e1759f77e1c8e25be51f264

test:
  secret_key_base: 278099ea2e5dc54462e662d76a0f1d1c1e45e415e53bd93aa54be7f93da595311ce9d5de5949917bfdc0ab4ee1a55b1b3212408f9b4a4be49723a5362ec7a4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
